### PR TITLE
Fix compilation issue in `CanotoSpec`

### LINKED ISSUE #98: `CanotoSpec` compilation issue with `zero` var
For certain types, the `zero` var is not used in the generated code which causes a compile error. For example:

```golang
// Input
type Get struct {
	Key []byte `canoto:"bytes,1"`

	canotoData canotoData_Get
}

// Output
func (*Get) CanotoSpec(types ...reflect.Type) *canoto.Spec {
	types = append(types, reflect.TypeOf(Get{}))
	var zero Get
	s := &canoto.Spec{
		Name: "Get",
		Fields: []*canoto.FieldType{
			{
				FieldNumber: 1,
				Name:        "Key",
				OneOf:       "",
				TypeBytes:   true,
			},
		},
	}
	s.CalculateCanotoCache()
	return s
}
```

### PR DESCRIPTION
**Pull request by dhrubabasu**
Resolves #98

### CODE REVIEW

File: internal/canoto.go [hunk 1]
```diff
@@ -193,3 +193,14 @@ type Scalars struct {
 
 	canotoData canotoData_Scalars
 }
+
+type CanotoSpecZeroVarUnneeded struct {
```
Comment (dhrubabasu) [inline internal/canoto.go:197]: This probably needs a better name

File: generate/canoto.go [hunk 2]
```diff
@@ -291,9 +294,32 @@ ${marshal}	return w
 		"storeSuffix":         storeSuffix,
 		"oneOfCacheAccessors": makeOneOfCacheAccessors(m),
 		"marshal":             makeMarshal(m),
+		"zero":                makeZeroVarName(m, generics),
 	})
 }
 
+func makeZeroVarName(m message, generics string) string {
+	staticTypes := []canotoType{
```
Comment (dhrubabasu) [inline generate/canoto.go:302]: Not super happy with this name... any suggestions welcome :)

Comment (StephenButtolph) [inline generate/canoto.go:302]:
```suggestion
	zeroIsUnusedTypes := []canotoType{
```
Would probably be the most verbose...

File: internal/canoto.go (hunk 1 above)
Comment (StephenButtolph) [inline internal/canoto.go:197]:
```suggestion
type SpecUnusedZero struct {
```

File: generate/canoto.go [hunk 3]
```diff
@@ -136,7 +137,7 @@ ${sizeCache}${oneOfCache}}
 // CanotoSpec returns the specification of this canoto message.
 func (*${structName}${generics}) CanotoSpec(types ...reflect.Type) *${selector}Spec {
 	types = append(types, reflect.TypeOf(${structName}${generics}{}))
-	var zero ${structName}${generics}
+${zero}
 	s := &${selector}Spec{
```
Comment (StephenButtolph) [inline generate/canoto.go:141]: Super nit picky, but it feels a bit odd to me that with `zero` there isn't a newline and without `zero` there is a newline... It feels like we should probably either always or never have the newline.
```suggestion
${zero}	s := &${selector}Spec{
```
(And append a newline to the value of `zero` if it is set)

**Review by StephenButtolph — COMMENTED** [review]
Also before this is merged we should probably bump the version to `.3` so that we can just tag the result of this PR

File: generate/canoto.go (hunk 3 above)
Comment (dhrubabasu) [reply generate/canoto.go]: went with no newline
